# This dockerfile is designed to be placed in a base directory
# with ./raspi containing the fully extracted raspberry pi disk image
# It will then copy that into the docker container, creating
# an arm container that has all the default raspberry pi ubuntu code
from scratch
COPY ./raspi /