#!/bin/sh

# Create the MSR user and setup their bashrc
/sbin/useradd msr --create-home --shell /usr/bin/bash --groups sudo,adm,video

echo "source /opt/ros/noetic/setup.bash" >> /home/msr/.bashrc
rosdep update

# The onetime_init service generates ssh keys on first boot and dumps network info (for debugging purposes) to /etc/network_info.txt
systemctl enable onetime_init.service
