#!/bin/sh
# Install ROS
curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

# Install some of the base system and libraries that are very useful for development, along with ROS
apt-get update \
    && apt-get install -y \
               build-essential \
               debhelper \
               dpkg-dev \
               ffmpeg \
               gdb \
               git \
               network-manager \
               libarmadillo-dev \
               libeigen3-dev \
               libopencv-dev \
               python3-bloom \
               python3-numpy \
               python3-scipy \
               python3-sympy \
               python3-serial \
               python3-rosdep \
               ros-dev-tools \
               ros-humble-ros-base \
               python3-rosinstall \
               python3-rosinstall-generator \
               python3-wstool \
               python3-vcstool \
               ssh \
               v4l-utils

rosdep init

systemctl enable ssh
