#!/bin/sh
# Install ROS
echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list

curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -

# Install some of the base system and libraries that are very useful for development, along with ROS
apt-get update \
    && apt-get install -y \
               build-essential \
               debhelper \
               dpkg-dev \
               ffmpeg \
               gdb \
               git \
               network-manager \
               libarmadillo-dev \
               libeigen3-dev \
               libopencv-dev \
               python3-bloom \
               python3-catkin-lint \
               python3-numpy \
               python3-scipy \
               python3-sympy \
               python3-serial \
               python3-rosdep \
               ros-noetic-ros-base \
               python3-rosinstall \
               python3-rosinstall-generator \
               python3-wstool \
               python3-vcstool \
               ssh \
               v4l-utils

rosdep init

systemctl enable ssh
